### ISSUE TITLE
Update Long-term unemployment data charts

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#112]
Long term unemployment rate: 

* Two tabs in separate charts - one is rolling 3 years, one is all time. First chart to be rolling 3 years. 
* Show both 6+ and 12+ months as separate series on each chart

Both to be 16-24 age range

**Comment by taz-chiles** [comment]
I have added the two charts for long term employment over 12 months, 3 years and for all time. 

https://data.youthfuturesfoundation.org/dashboard/labour-market/

Each chart has two series - one for 12 months and another for 6 months. 

May need to review content and exact wording @ODILMichelle @gilesdring

**Comment by ODILMichelle** [comment]
Additional comment:
The hovertool top label seems to have different settings on different visualisations. 

Blue line, on long term unemployment (all data) shows the date, number and then percentage sign - which is the same approach taken on the NEET visualisation (https://data.youthfuturesfoundation.org/dashboard/neet/). 

None of the hover tooltip labels do this. Our approach should be the same across the site. @taz-chiles & @gilesdring can you agree what our approach will be? And as part of that review whether the data format in these hover labels will be numerical format (e.g. 2022-07-01) or text format (e.g. July - Sept 2022), and ensure these are the same.

**Comment by ODILMichelle** [comment]
@gilesdring @t picking up on other changes on this page, the points raised above might now be done, bar two questions:

1. Do we want to remove the titles on this page (to ensure this is kept in alignment with the NEET page)
2. Do we want to add '(SA)' to the tags, again to harmonise with approach taken on NEET data

And just finally, the second tab 'Long term unemployment, all data' - I was wondering if we name this 'Long term unemployment, since 1992' or similar. I don't think 'all data' will mean much to a viewer who isn't deeply immerse in this space.
