### ISSUE TITLE
Extract 6+ months unemployment stats from UNEM01 data source

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#113]

**Comment by taz-chiles** [comment]
I believe I have completed this ticket as part of [Update Long-term unemployment data charts#112](https://github.com/open-innovations/yff-data/issues/112)

6 month data now being pulled into 'long_term_unemployed_all_data' and 'long_term_unemployed_last_3_years' datasets and summarised in 'headlines.csv'. 

@gilesdring let me know if this is not what this ticket refers to, otherwise this ticket can be closed.

**Comment by gilesdring** [comment]
I think this is correct - I've relabelled the data as 6-12 months to avoid confusion.
