### ISSUE TITLE
Update QLFS pipeline to extract data for 16-24 YO in FTE

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#115]

**Comment by taz-chiles** [comment]
I believe I have completed this ticket as part of [Update QLFS charts derived from A06#114](https://github.com/open-innovations/yff-data/issues/114)

I have updated the pipeline to pull 'in full-time education' data into the same dataset. Let me know if this is not what this ticket refers to, otherwise if you're all happy with the changes I have made then this can be closed.

**Comment by taz-chiles** [comment]
@gilesdring I've updated file and variable names from 'not_in_education' to 'education_status', as these now include 'in full-time education' data

**Comment by gilesdring** [comment]
Looks OK to me!
