### ISSUE TITLE
Improve tooltip text visibility on dashboard landing page

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#185]
When viewing the visualisations on the dashboard landing page (https://data.youthfuturesfoundation.org/), the tooltip hover text is not always visible (see attached image).

Not tested this on mobile, but we should also check this.

![Image](https://github.com/open-innovations/yff-data/assets/88284441/e1945386-fe34-4431-aa4e-4cb6134a2d0c)

**Comment by ODILMichelle** [comment]
This might be something @slowe can help us with?

**Comment by gilesdring** [comment]
Probably better to remove interactivity from these (as well as potentially improving presentation of axes on very small graphs #150 )

**Comment by slowe** [comment]
I'm just about to commit a change that behaves like this. ![yff-example](https://github.com/open-innovations/yff-data/assets/299787/f492dc48-975f-447d-89b6-b3dc16ece44e)

**Comment by ODILMichelle** [comment]
Looks grand on computer, but doesn't seem to work on phone. 

Will it be an easy fix to get it to work on phones, or do we want to remove this interactivity and make these static images as we discussed earlier?

**Comment by slowe** [comment]
@ODILMichelle When you say "doesn't seem to work on phone" what does that mean? The popup does break out of the containing box on narrow screens. Are you looking at a cached version of the page? To remove interactivity we would need to design a way to define which things get interactivity and which don't. So that would need thought and work about exactly what is required and the problems that might result.

**Comment by slowe** [comment]
@ODILMichelle Thanks for updating with a screenshot. This is covered by "some of the tooltip isn't visible in some circumstances" although it is a different circumstance and cause to the initial screenshot so it is good to know that.
