### ISSUE TITLE
Remove dashed border from key item when you've clicked the item a second time

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#203]
When you 'click off' a certain key item, as some might do, you end up with a dashed line (see screen shot), which is a little confusing given what happens 

![Image](https://github.com/open-innovations/yff-data/assets/88284441/f4c2afd3-576d-4c00-a3fe-5c84c01bcc44)

**Comment by slowe** [comment]
@ODILMichelle This is happening because you are still hovering/focussed on the key item. I appreciate it may be momentarily confusing. The only way I could see to stop that was to (technical term) blur focus from the key item when you unlock the series. However, doing that proved less than helpful for people using keyboard navigation (e.g. if you are using a screenreader) as they then were "kicked off" the item and had to navigate back to it.

**Comment by ODILMichelle** [comment]
I also see it when I'm not hovering over the item (see attached). If there isn't a way to fix it, then so be it! 

<img width="1280" alt="Screenshot 2023-06-08 at 11 07 03" src="https://github.com/open-innovations/yff-data/assets/88284441/9624801d-c68f-4fdc-b76b-1200693f48f2">

**Comment by slowe** [comment]
Yes, your browser still has `focus` set to the key item even if your cursor is moving somewhere else (because you clicked it). If you click somewhere else on the page (to set the focus to somewhere else) the style will go.

**Comment by ODILMichelle** [comment]
Lets ignore this for now & worry about it if anyone asks us for us.
