### ISSUE TITLE
Decide whether we want to space tick labels by 2, 3 or 6 months

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#221]
After feedback in the last show & tell, it was asked whether we can space out x axis tick labels by each quarter. Currently tick labels are shown every 6 months. 

We should consider how this will behave with larger datasets as the chart could become cluttered with smaller intervals. 

Do we want to remain at 6 months or shorten the intervals ?

**Comment by gilesdring** [comment]
Auto ticks are on a sequence unrelated to annual. If they end up being every 6 months it's probably cause it's quarterly data and picking every other. Would be good to be a bit more intentional about this. I was suggesting during the call that we maybe look at 2, 3, 6, 12, 18, 24, 36, etc as sensible sequences of months. There might be tuning on how close we want to allow the labels to become. Related to #179, so propose we hang off until that one is sorted

**Comment by ODILMichelle** [comment]
It's in sprint 8, no rush. Will add blocked so no-one dives into it for now.

**Comment by taz-chiles** [comment]
Closing #221 as not planned, we can come back to this if we need to update visualisations in the next phase.
